### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stoneface86** [stoneface86/trackerboy#10]
This issue will serve as a roadmap for planned features. Feel free to suggest new features here, or discuss any of the planned features.
Note that the roadmap may change at any time, as certain features may be prioritized as necessary. Reminder that this repo is for the front end of Trackerboy, so some features requested may require back end support (libtrackerboy). libtrackerboy's roadmap is located [here](https://github.com/stoneface86/libtrackerboy/issues/2)

Items in bold are features that are **required for release**. Once all required features are implemented, the first release version (v1.0.0) will be published. There is no schedule for this version, since it only depends on all requirements being implemented.

## v0.7.0  (requires libtrackerboy v0.3.0)

 - [ ] **Overhaul Instrument Editor to utilize new envelope sequences**
   - [ ] **Remove Initial envelope settings**
   - [ ] **Add a sequence editor for envelope**
   - [ ] **Implement an envelope editor for volume envelopes**
   - [ ] **Implement a wave macro editor for CH3 envelopes**
 - [ ] **Allow the user to set the loop index for a sequence graphically**
 - [ ] Add per-song timing option in Module Properties dialog
 - [ ] **Implement Instrument/Waveform import and export**
 - [ ] Add `>>` row to OrderEditor (see below)

### `>>` row

Adds a row to the order editor at the end that allows the user to append a new row with the specified track ids
![image](https://user-images.githubusercontent.com/44489054/180967256-03423e67-7a8a-4f6f-af87-9c44d4dcefbb.png)
When the user hits enter, a row with the entered ids will be inserted, or an automatic id will be used instead

## v0.8.0 (requires libtrackerboy v0.4.0)

 - [ ] Add support to pattern editor for new effect `6xx`

## v0.9.0 (requires libtrackerboy v0.5.0)

 - [ ] **Add `.asm` exporter dialog**
 - [ ] **Add `.gbs` exporter dialog**
 - [ ] **Add `.vgm` exporter dialog**

## v0.10.0

 - [ ] **Pattern editor horizontal scrolling**
 - [ ] **Channel volume meters**
 - [ ] **Volume meter toolbar (similar to OpenMPT's)**

## v0.11.0 (requires libtrackerboy v0.6.0)

 - [ ] **Add vibrato style option to Module Properties dialog**

## Unplanned

- [ ] `.mod` importer dialog
- [ ] Grooves, or speed sequences
- [ ] FamiTracker integration
  - [ ] Clipboard support
  - [ ] Import from `.ftm`
- [ ] Sound effects
  - [ ] Sound effect editor
  - [ ] Sound effect list view + model
  - [ ] Sound effect rendering
- [ ] UI Fluff
  - [ ] Instrument preview tracking
  - [ ] Show register state
  - [ ] Channel scopes
  - [ ] Spectrum visualizer
- [ ] Export to other driver formats
  - [ ] Pokemon sound engine
  - [ ] Rockman World 2 Driver

## Discussion

Feel free to comment below if you have any suggestions with the roadmap outlined above. For feature requests, please create a separate issue, which I will then add to the roadmap if the request is doable.

**Comment by sttng** [comment]
- OpenMPT clipboard support
